### ISSUE TITLE
Incorrect display of colored passsords in entry list

### ISSUE THREAD

**Issue by TBugReporter** [Rookiestyle/ColoredPassword#1] opened 2020-08-13 07:16 UTC
See [your SourceForge thread](https://sourceforge.net/p/keepass/discussion/329220/thread/8abbde95ec/#2be0) for a screenshot.

**Comment by Rookiestyle** [comment] 2020-08-13 20:10
As already mentioned, a debug file would be good to further analyze the issue you're facing.

If you want to attach it here, you might need to rename it from .xml to .txt

**Comment by Rookiestyle** [comment] 2020-08-14 11:12
This issue is caused by the QualityHighlighter plugin and I needed to adjust my workaround to bypass its shortcoming.
I created a fix and would like you to test it before I publish it, get it here: https://github.com/Rookiestyle/ColoredPassword/releases/tag/v0.9.0.1

**Comment by TBugReporter** [comment] 2020-08-14 19:55
I disabled QH, but didn't uninstall it, since I do find it convenient when reviewing passwords - but apparently disabling it doesn't disable it completely.  0.9.1 works better, but still shows some "invisible" characters - like the @ and % in the new screenshot I posted at SourceForge (I don't see a way to do that here).

**Comment by TBugReporter** [comment] 2020-08-14 19:58
I disabled QH, but didn't uninstall it, since I do find it convenient when reviewing passwords - but apparently disabling it doesn't disable it completely.  0.9.1 works better, but still shows some "invisible" characters - like the @ and % in the new screenshot I posted at SourceForge (I don't see a way to do that here).

**Comment by TBugReporter** [comment] 2020-08-14 19:58
I disabled QH, but didn't uninstall it, since I do find it convenient when reviewing passwords - but apparently disabling it doesn't disable it completely.  0.9.1 works better, but still shows some "invisible" characters - like the @ and % in the new screenshot I posted at SourceForge (I don't see a way to do that here).

**Comment by Rookiestyle** [comment] 2020-08-15 21:27
It seems, that not only some characters are not shown but also the column showing the password quality is shown without text as well as the 'P' in the following entries' password is colored green.
I downloaded all the plugins you use and can't reproduce it.

Can you attach your KeePass config file please, so that I can test with the same settings you have? Save it as *.txt, you can't attach xml files here.

If it's not related to the config, maybe it's related to Windows 7 and I can't test that.
Does it work if you remove QH?
Does it work properly if you remove all plugins except ColoredPassword?


> ... screenshot ...(I don't see a way to do that here)

Click *Attach files by dragging & dropping, selecting or pasting them.*

**Comment by TBugReporter** [comment] 2020-08-15 23:35
> the column showing the password quality is shown without text

True - and with my real databases, most of the time the User Name column is also blank.

> the 'P' in the following entries' password is colored green.

That's just my settings - changed to match Strongbox on the iPhone.

> Can you attach your KeePass config file please

Done.  [KeePass.config.xml.txt](https://github.com/Rookiestyle/ColoredPassword/files/5079734/KeePass.config.xml.txt)  (Note that there are probably a lot of very strange settings in there, because I'm always playing with the settings - in an effort to better understand and [document](https://sourceforge.net/u/t_bugreporter/wiki/KPconfig/) them.)

> Does it work if you remove QH?
> Does it work properly if you remove all plugins except ColoredPassword?

No on both counts - pretty much the same.

> Click _Attach files by dragging & dropping, selecting or pasting them_.

Duh - I was looking for an icon above the text box.

**Comment by Rookiestyle** [comment] 2020-08-16 16:24
OK, two issues:

1. I deactivate QH and call it's coloring routine within mine and I missed one spot. Should be fixed now.
2. Windows 7 calculates character widths in an inconsistent way. This lead to the calculated width for some characters being to small and nothing being drawn instead. I changed this to accomodate for that.

Please try https://github.com/Rookiestyle/ColoredPassword/releases/tag/v0.9.0.1
It's the best I can do, anything more needs to be done by the author of QH.

I'll release this dev version 0.9.0.1 as 0.9.1 in the next days.

**Comment by TBugReporter** [comment] 2020-08-17 00:06
This improves the display of actual passwords, but not of the other columns.  Apparently, every color change requires an additional string, but the other columns (which don't require any color changes - or for that matter, any changes at all) don't display at all when the string doesn't fit the column width.  You don't touch the title column at all; why do you have to touch the others?

**Comment by Rookiestyle** [comment] 2020-08-17 12:59
> You don't touch the title column at all; why do you have to touch the others?

The first column (subitem) contains a reference to the entire line (item) and does not require special handling.
Initially I let the OS draw all columns except the password column but this lead to issues on Linux (mono).

The updated now let's Windows draw everything except the password in standard mode, while all columns will be rendered manually when running on Linux.
Please retest https://github.com/Rookiestyle/ColoredPassword/releases/tag/v0.9.0.1

**Comment by TBugReporter** [comment] 2020-08-17 18:57
Latest version works, except if there are spaces in the Password field; those aren't showing, e.g. a credit card number "1234 5678 9012 3456" is showing as "1234567".

**Comment by Rookiestyle** [comment] 2020-08-17 19:38
This is now fixed as well, the dev version 0.9.0.1 is updated.

I'll do some code cleanup tomorrow (mainly adding comments for all those OS specific tweaks) and release it as 0.9.1

**Closed as completed** 2020-08-18 17:20 UTC
Labels: bug, enhancement

**Comment by Rookiestyle** [comment] 2020-08-18 17:24
I released version 0.9.1
Thanks for your support in testing the fix

**Comment by TBugReporter** [comment] 2020-08-20 00:14
Thank _**you**_ for putting up with my weird configuration; you really went above and beyond the call here. :-)
